version: "3.9"

services:
  pg_db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
  avito-app:
    build: ./
    command: "./bin/server"
    depends_on:
      pg_db:
        condition: service_started
    ports:
      - "8080:8080"
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
  #   ports:
  #     - "5050:80"